---
# tasks file for environment/roles/win-ad-feature


 - name: Create new Windows domain in a new forest with specific parameters
   win_domain:
      create_dns_delegation: no
      database_path: C:\Windows\NTDS
      dns_domain_name: "{{ domain_name }}"
      domain_mode: Win2012R2
      domain_netbios_name: "{{ netbios_name }}"
      forest_mode: Win2012R2
      safe_mode_password: "{{ safe_mode_password }}"
      sysvol_path: C:\Windows\SYSVOL
      reboot_required: always
   register: domain_install
